# .github/workflows/run.yml

name: Classificar Empresas RPE

on:
  workflow_dispatch:

jobs:
  run-script:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas openpyxl playwright
          playwright install chromium

      - name: Run script
        run: |
          python -u classificar_empresas_rpe.py

      - name: Upload resultado
        uses: actions/upload-artifact@v4
        with:
          name: classificacao_empresas
          path: classificacao_empresas.xlsx
